### ISSUE TITLE
design an appealing UI

### ISSUE THREAD

**Issue by YuqingCheng** [YuqingCheng/cs5610-project-1#10]
design an UI that looks minimal, straightforward but not looking like a rough demo

**Comment by Cappuccinuo** [comment]
3.10 Fix the index page to simple skeleton, need change the background color/picture, fix the room list to the right of page. The game page pending style.

**Comment by Cappuccinuo** [comment]
Need to replace the logo of Othello.

**Comment by Cappuccinuo** [comment]
![image](https://user-images.githubusercontent.com/13606791/37860070-c96bd74a-2ef4-11e8-9a47-28b612460f9a.png)
Index

**Comment by Cappuccinuo** [comment]
![image](https://user-images.githubusercontent.com/13606791/37860073-d2a53b30-2ef4-11e8-8d01-d283481d0def.png)
Lobby

**Comment by Cappuccinuo** [comment]
![image](https://user-images.githubusercontent.com/13606791/37860084-dc0e50bc-2ef4-11e8-8290-f727c0055d50.png)
Game

**Comment by Cappuccinuo** [comment]
![screen shot 2018-03-25 at 11 41 54 am](https://user-images.githubusercontent.com/13606791/37883282-8560d800-3077-11e8-9495-3f9e6e74a252.png)
