### ISSUE TITLE
Submit form in the index page when hit enter

### ISSUE THREAD

**Issue by Cappuccinuo** [YuqingCheng/cs5610-project-1#12]
I use
`<script>
    $(document).keypress(function(event) {
      if (event.keyCode == 13) {
        window.location=document.getElementById('enter').href;
      }
    });
</script>`
to redirect window to new href in templates/page/index.html.eex,
but the index.jsx doesn't response. When I hit enter, it redirect me to /?
I tried to alert to see if I can get the href by above code, it turns out that the code has no problem.

**Comment by YuqingCheng** [comment]
It looks like the form has passed the value in it as parameter in the path after '?'.. is this what is supposed to be like？

**Comment by Cappuccinuo** [comment]
Solved.
[Submit Form in React Example](http://jsfiddle.net/ferahl/b125o4z0/)
```
<form onSubmit={function(e) {
            e.preventDefault();
            window.location=link;
          }}>
            <div className="input">
              <input onKeyUp={this.handleChange} placeholder={'Enter game name'}/>
              <button id="enter" type="submit" color='success'>Join Game</button>
            </div>
        </form>
```
