### ISSUE TITLE
Need refresh to see side bar change after players leave

### ISSUE THREAD

**Issue by Cappuccinuo** [YuqingCheng/cs5610-project-1#22]
![screen shot 2018-03-25 at 10 03 38 pm](https://user-images.githubusercontent.com/13606791/37883459-80c82f86-3078-11e8-9885-acfe4ff3aa2b.png)
After I hit ok.
![screen shot 2018-03-25 at 10 03 44 pm](https://user-images.githubusercontent.com/13606791/37883461-84257bb6-3078-11e8-8f0a-abc32fcec425.png)
After I refresh.
![screen shot 2018-03-25 at 10 03 49 pm](https://user-images.githubusercontent.com/13606791/37883462-86f5ee52-3078-11e8-8833-8a786e2b1193.png)
Is this a big issue?

**Comment by YuqingCheng** [comment]
Thank you for bringing up this, I will add the sidebar update to the call-back when user leaves!
