### ISSUE TITLE
Implement Disk Component

### ISSUE THREAD

**Issue by Cappuccinuo** [YuqingCheng/cs5610-project-1#5]
Disk has several attributes: 
Color (White, Black, Transparent, initial state is Transparent)
Server will change the color based on the current board.

**Comment by Cappuccinuo** [comment]
The move function I haven't quite understand, so I split the disk into another jsx file, we can add hint func in this file. 

The click is not working right now.

**Comment by Cappuccinuo** [comment]
Also, the initial of colors array in elixir, it should assign the disks in the middle with
1, 2
2, 1

**Comment by YuqingCheng** [comment]
You can make disk a seperate jsx file, and put move function in this jsx file. Move function is the function that triggers backend state to update at server side. And updateView function is the function that triggers frontend state to update in React, so you need do some change in Disk to let it receive updateView as props if you want to make it a seperate jsx file

**Comment by YuqingCheng** [comment]
I updated the disks in the middle at backend
